version: 0.2

phases:
  install:
    commands:
      - sudo yum install -y wget tar

  build:
    commands:
      - wget https://github.com/filebrowser/filebrowser/releases/download/v2.32.0/linux-amd64-filebrowser.tar.gz
      - tar -xvf linux-amd64-filebrowser.tar.gz
      - sudo mv filebrowser /usr/local/bin/
      - sudo chmod +x /usr/local/bin/filebrowser

  post_build:
    commands:
      - mkdir -p /home/ec2-user/filebrowser
      - echo "Starting File Browser in the background..."
      - nohup filebrowser -r /home/ec2-user/filebrowser -p 8080 > /home/ec2-user/filebrowser.log 2>&1 &
      - echo "File Browser started successfully."

artifacts:
  files:
    - /home/ec2-user/filebrowser.log
